apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata: 
      labels:
        app: django
    spec:
      containers:
        - name: django-server
          image: shriefzain/server-django:latest
          ports:
          - containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              value: userdb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: django
