# Generated by Django 4.2.3 on 2024-04-25 02:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),  # Assuming you have this field
                # Add other fields as needed
            ],
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: [
                User.objects.create(user="John Doe"),
                User.objects.create(user="Jane Smith"),
                # Add more users as needed for initial data
            ],
            reverse_code=lambda apps, schema_editor: User.objects.all().delete(),
        ),
    ]    
